### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by derpoliuk** [eggheadgames/apple-error-handling#10]
More info here: https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by salutis** [comment]
Why are we using CocoaPods again? I thought it Carthage from now on.

CC: @mikemee

**Comment by derpoliuk** [comment]
I copy-pasted this issue from [ReceiptKit](https://github.com/eggheadgames/ReceiptKit). We have no CocoaPods support yet.

I'll update title and move it to `undecided` milestone.

**Comment by mikemee** [comment]
> Why are we using CocoaPods again? I thought it's Carthage from now on.

@salutis Because if it's cheap to add, and causes no problems for us, it contributes back to the open source community even more than just Carthage.

**Comment by salutis** [comment]
@mikemee 

> ... if it's cheap to add, and causes no problems for us ...

No.

It goes against YAGNI. If we don't use it, it won't be maintained. If it's not maintained, it's not going to work. Also, that's not how open source works. If somebody wants CocoaPods support, they will contribute.

Also, it's not cheap. Besides, why in the world would you pay for something nobody uses?

**Comment by salutis** [comment]
We don't need CocoaPods. Closing.
